=== queries-are-us/public_data-sets/lib/data_types/education.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "description": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "link": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "title": {
            "type": "string"
        }
    },
    "type": "object"
}

=== queries-are-us/public_data-sets/data_sets/education/education_dataset.json
[
    {
        "id": "N5q3Q8-safari-books-online",
        "name": "Safari® Books Online",
        "title": "O'Reilly Media - Technology and Business Training",
        "link": "https://www.oreilly.com/",
        "description": "Gain technology and business knowledge and hone your skills with learning resources created and curated by O'Reilly's experts: live online training, video, books, our platform has content from 200+ of the world's best publishers."
    },
    {
        "id": "7u3wp5-coursera",
        "name": "Coursera",
        "title": "Coursera | Degrees, Certificates, & Free Online Courses",
        "link": "https://www.coursera.org/",
        "description": "Learn new job skills in online courses from industry leaders like Google, IBM, & Meta. Advance your career with top degrees from Michigan, Penn, Imperial & more."
    },
    {
        "id": "TJeVjP-pluralsight",
        "name": "Pluralsight",
        "title": "Pluralsight | The tech workforce development company",
        "link": "https://www.pluralsight.com/",
        "description": "Access the technology workforce development platform that helps tech teams know more and work better together with stronger tech skills, processes and leaders."
    },
    {
        "id": "UxlSQm-khan-academy",
        "name": "Khan Academy",
        "title": "Khan Academy | Free Online Courses, Lessons & Practice",
        "link": "https://www.khanacademy.org/",
        "description": "Learn for free about math, art, computer programming, economics, physics, chemistry, biology, medicine, finance, history, and more. Khan Academy is a nonprofit with the mission of providing a free, world-class education for anyone, anywhere."
    },
    {
        "id": "CxUumZ-udemy",
        "name": "Udemy",
        "title": "Online Courses - Learn Anything, On Your Schedule | Udemy",
        "link": "https://www.udemy.com/",
        "description": "Udemy is an online learning and teaching marketplace with over 204,000 courses and 54 million students. Learn programming, marketing, data science and more."
    },
    {
        "id": "4TQe57-skillshare",
        "name": "Skillshare",
        "title": "Online Learning: Creative Classes on Skillshare",
        "link": "https://www.skillshare.com/",
        "description": "Skillshare is an online learning platform with thousands of creative courses and classes taught by experts to help you learn new skills."
    },
    {
        "id": "A43pkN-codecademy",
        "name": "Codecademy",
        "title": "Learn to Code - for Free | Codecademy",
        "link": "https://www.codecademy.com/",
        "description": "Learn the technical skills to get the job you want. Join over 50 million people choosing Codecademy to start a new career (or advance in their current one)."
    },
    {
        "id": "UxmIRO-dotnetos",
        "name": "Dotnetos",
        "title": "Home - Dotnetos - courses & conferences about .NET",
        "link": "https://dotnetos.org/",
        "description": "We help build correct, robust and efficient .NET solutions."
    },
    {
        "id": "tQI5KK-frontendmasters",
        "name": "Frontend Masters",
        "title": "Frontend Masters — Learn JavaScript, React, Vue & Angular from Masters of Front-End Development!",
        "link": "https://frontendmasters.com/",
        "description": "Advance your skills with in-depth, modern JavaScript and front-end engineering courses."
    }
]
