=== queries-are-us/public_data-sets/lib/data_types/podcasts.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "address": {
            "type": "string"
        },
        "descriptions": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "tags": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "title": {
            "type": "string"
        }
    },
    "type": "object"
}

=== queries-are-us/public_data-sets/data_sets/podcasts/podcasts_dataset.json
[
    {
        "id": "OnApFi-dotnet-rocks",
        "title": ".NET Rocks! vNext",
        "address": "https://dotnetrocks.com",
        "tags": [
            "tech",
            "software developers",
            "dotnet"
        ],
        "descriptions": ".NET Rocks! is a weekly talk show for anyone interested in programming on the Microsoft .NET platform. The shows range from introductory information to hardcore geekiness."
    },
    {
        "id": "ZUnKsS-darknetdiaries",
        "title": "Darknet Diaries â€“ True stories from the dark side of the Internet.",
        "address": "https://darknetdiaries.com/",
        "tags": [
            "tech",
            "darknet",
            "darkweb",
            "stories",
            "crypto",
            "hacking",
            "infosec",
            "security"
        ],
        "descriptions": "A podcast featuring true stories from the dark side of the Internet."
    }
]
